version: "2.1"

volumes:
  pihole_config: {}
  dnsmasq_config: {}
  tailscale: {}

services:
  pihole:
    image: pihole/pihole:latest
    cap_add:
      - NET_ADMIN
    depends_on:
      - cloudflared
    volumes:
      - "pihole_config:/etc/pihole"
      - "dnsmasq_config:/etc/dnsmasq.d"
    dns:
      - "127.0.0.1"
      - "1.1.1.1"
    network_mode: host
    tmpfs:
      - /var/log/pihole
    environment:
      PIHOLE_DNS_: 127.0.0.1#5053;127.0.0.1#5053
      WEB_BIND_ADDR: 0.0.0.0

  cloudflared:
    image: cloudflare/cloudflared:latest
    command: proxy-dns --port 5053
    network_mode: host

  # https://github.com/balenablocks/hostname
  hostname:
    build: hostname
    restart: no
    labels:
      io.balena.features.supervisor-api: 1
    environment:
      SET_HOSTNAME: pihole

  tailscale:
    image: tailscale/tailscale:latest
    network_mode: host
    restart: on-failure
    volumes:
      - tailscale:/var/lib/tailscale
    labels:
      - io.balena.features.kernel-modules=1
    cap_add:
      - net_admin
      - net_raw
      - sys_module
    tmpfs:
      - /tmp
      - /var/run/
    environment:
      TS_EXTRA_ARGS: --accept-dns=false --reset
      TS_STATE_DIR: "/var/lib/tailscale"
      TS_SOCKET: "/var/run/tailscale/tailscaled.sock"
